name: infix_expression_tree_converter
description: A command line app used to convert an infix expression into its postfix and prefix notations.
version: 1.0.0

environment:
  sdk: '>=2.15.1'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
dependencies: 
  stack: ^0.2.1
