name: infix_expression_converter
description: A package used to convert an infix expression into its postfix and prefix notations.
version: 1.0.0

environment:
  sdk: '>=2.15.1'

executables:
  main:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.20.1
dependencies: 
  args: ^2.3.0
  stack: ^0.2.1
  string_validator: ^0.3.0
